---
   - name: Copying the Dockerfile
     copy:
        src: Dockerfile
        dest: /home/ec2-user
   - name: Build Docker image from Dockerfile
     docker_image:
        name: apache
        path: /home/ec2-user
        state: build

   - name: Running the container
     docker_container:
         name: apache_demo
         image: apache 
         state: present
   - name: Running the container
     docker_container:
         name: apache_demo
         tty: yes
         interactive: no
         published_ports: 80:80
         state: started

#   - name: Start docker
#     shell:  docker run --name hello --publish-all -t -d web1:latest
#   - name: Check if container is running
#     shell: docker ps

