---
apiVersion: v1
kind: Pod
metadata:
   name: Tomcat
spec:
   containers:
   - name: Tomcat
    image: tomcat: 8.0
    ports: 81
containerPort: 7500
   imagePullPolicy: Always
   - name: Database
     Image: mongoDB
     Ports: 82
containerPort: 7501
   imagePullPolicy: Always
